local rand = require "xoshiro256starstar"

local seed = 123454321
local seq = {}

math.randomseed(seed)
for _ = 1, 20 do
  table.insert(seq, math.random())
end
for _ = 1, 20 do
  table.insert(seq, math.random(10000))
end
for _ = 1, 20 do
  table.insert(seq, math.random(7890, 11434))
end

print("Sequence generated by math.random:")
print(table.concat(seq, " "))

local seq2 = {}
local gen = rand(seed)
for _ = 1, 20 do
  table.insert(seq2, gen:random())
end
for _ = 1, 20 do
  table.insert(seq2, gen:random(10000))
end
for _ = 1, 20 do
  table.insert(seq2, gen:random(7890, 11434))
end

print("Sequence generated by custom rand:")
print(table.concat(seq2, " "))

for i = 1, 60 do
  if seq[i] ~= seq2[i] then
    error("Test failed! The random generator doesn't work samely as standard random function.")
  end
end
